- name: Configuracion del sitio apache
  template:
    src: templates/ansible_site.conf.j2
    dest: /etc/apache2/sites-available/ansible_site.conf

- name: Activa el nuevo sitio
  command: a2ensite ansible_site.conf

- name: Deshabilita el sitio default
  command: a2dissite 000-default.conf

- name: Cambiar el e-mail del webmaster
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: 'ServerAdmin webmaster@localhost'
    line: '	ServerAdmin webmaster@educacionit.com'




    