pipeline {
    agent any
    
    stages {
        stage("Ejecutar ansible playbook") {
            steps {
                sh "whoami"
                sh "pwd"
                sh "ansible-playbook -i ./Desafio_6/ansible_Desafio6/inventory.ini ./Desafio_6/ansible_Desafio6/main.yml"

            }
        }
    }
}