pipeline {
    agent any
    
    stages {
        stage("Ejecutar ansible playbook") {
            steps {
                sh "whoami"
                sh "pwd"
                sh "ls"
                sh "ansible-playbook -i ./ansible_Desafio6/inventory.ini ./ansible_Desafio6/main.yml"

            }
        }
    }
}