apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: MONGO_DB_NAME
              value: db-desafio10-app
            - name: MONGO_DB_PASS
              value: s3cr3t!
            - name: MONGO_DB_URI
              value: mongodb://db-server:27017
            - name: MONGO_DB_USER
              value: root
            - name: PORT
              value: "3000"
          image: rcarbonatto/desafio_11:v1
          name: desafio11-app
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always

