pipeline {
    agent any
    tools {
        nodejs 'nodejs22.8.0'
    }   
    stages {
        stage("Installing dependencies npm") { //A free, open-source registry and package manager for JavaScript software packages
            steps {
                sh "sudo apt install npm"
                         
            }
        }
        stage("Run Test"){
            steps{
                sh "sudo npm test"
            }
        }
    }
}