pipeline {
    agent any
    tools {
        nodejs 'nodejs22.8.0'
    }
    stages {
        stage('Install Npm') {
            steps {
                echo "Ejecutar npm install" 
                
                sh 'sudo apt -y install npm'
                sh 'sudo apt -y install jest'
            }
        }

        stage('Test') {
            steps {
                echo "Ejecutar npm test push" 
                sh "cd ./Desafio_2/nodejs-helloworld-api && npm test"
             
            }
        }
    }
}