pipeline {
    agent any
    tools {
        nodejs 'nodejs22.8.0'
    }
    stages {
        stage('Build') {
            steps {
                echo "Ejecutar npm install" 
                sh 'cd ./Desafio_2/nodejs-helloworld-api/'
                sh 'sudo apt -y install npm'
            }
        }

        stage('Test ') {
            steps {
                echo "Ejecutar npm test push" 
                sh 'npm test'
            }
        }
    }
}