apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charthellmmify.fullname" . }}-app
  labels:
    io.kompose.service: app
  {{- include "charthellmmify.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f ..\docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      io.kompose.service: app
    {{- include "charthellmmify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.service: app
      {{- include "charthellmmify.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f ..\docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      containers:
      - env:
        - name: MONGO_DB_NAME
          value: {{ quote .Values.app.desafio11App.env.mongoDbName }}
        - name: MONGO_DB_PASS
          value: {{ quote .Values.app.desafio11App.env.mongoDbPass }}
        - name: MONGO_DB_URI
          value: {{ quote .Values.app.desafio11App.env.mongoDbUri }}
        - name: MONGO_DB_USER
          value: {{ quote .Values.app.desafio11App.env.mongoDbUser }}
        - name: PORT
          value: {{ quote .Values.app.desafio11App.env.port }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.app.desafio11App.image.repository }}:{{ .Values.app.desafio11App.image.tag
          | default .Chart.AppVersion }}
        name: desafio11-app
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
      restartPolicy: Always