name: Build and Push Docker Desafio 9

on:
    push:
        branches: [main]  # Set this to the branch that should trigger the build
        paths:
            - "Desafio_9/**"    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Desafio_9/Dockerfile
        push: true
        tags: rcarbonatto/desafio9_educacionit:latest  # Replace with your Docker Hub username/repository

    - name: Log out from Docker
      if: always()
      run: docker logout        